### ISSUE TITLE
Content-Type not cached

### ISSUE THREAD

**Issue by HVEVB** [jpresagios/express-api-cache#1]
Hi!

When a response had a content type header, the cached response version doesn't include it. It's instead defaulted to `text/html; charset=utf-8`

**Comment by jpresagios** [comment]
Hi!

@HVEVB  Thanks for the feedback, I will be working on it :))

**Comment by jpresagios** [comment]
Hi @HVEVB 
Was create a cache object to have a better representation of things to cache from original API response. Now
headers content type and status code  (200, 201, ...)  is present in the cache and returned from it :)
Please any feedback is more than welcome :))
